version: '3.9'

volumes:
  node-ipc:

networks:
  default:
    name: liqwid-bots

services:
  init-container:
    build:
      dockerfile: init-container/Dockerfile
      context: .
      no_cache: true
    environment:
      - CARDANO_NODE_DATA_FOLDER=/data
    volumes:
      - ${PWD}/data:/data
    restart: no
  cardano-node:
    image: inputoutput/cardano-node:8.1.1
    restart: always
    environment:
      - NETWORK=mainnet
    volumes:
      - ${PWD}/data:/data
      - node-ipc:/ipc
    depends_on:
      init-container:
        condition: service_completed_successfully
    healthcheck:
      test: bash -c '[ -S /ipc/node.socket ]'
      interval: 3m
      retries: 60
  ogmios:
    image: cardanosolutions/ogmios:v5.5.6-mainnet
    restart: always
    command:
      - --node-config
      - /config/cardano-node/config.json
      - --node-socket
      - /ipc/node.socket
      - --host
      - 0.0.0.0
      - --port
      - "1337"
      - --log-level
      - Info
    volumes:
      - node-ipc:/ipc
    depends_on:
      cardano-node:
        condition: service_healthy
  kupo:
    image: cardanosolutions/kupo:v2.4.1
    restart: always
    command:
      - --node-config
      - /config/cardano-node/config.json
      - --node-socket
      - /ipc/node.socket
      - --host
      - 0.0.0.0
      - --port
      - "1337"
      - --in-memory
      - --prune-utxo
      - --since
      - 83735993.ddeb4bf0e1daf4b510afaf479a48ae23570c10cea5f373f4077e850c0e21495d
      - --match
      - '*/*'
      - --log-level
      - Info
    volumes:
      - node-ipc:/ipc
    depends_on:
      cardano-node:
        condition: service_healthy
