version: '3.9'

volumes:
  node-ipc:

networks:
  default:
    name: liqwid-bots

services:
  init-container:
    build:
      dockerfile: init-container/Dockerfile
      context: .
      no_cache: true
    environment:
      - CARDANO_NODE_DATA_FOLDER=/data
    volumes:
      - ${PWD}/data:/data
    restart: no
  cardano-node:
    image: inputoutput/cardano-node:8.1.1
    restart: always
    environment:
      - NETWORK=mainnet
    volumes:
      - ${PWD}/data:/data
      - node-ipc:/ipc
    depends_on:
      init-container:
        condition: service_completed_successfully
    healthcheck:
      test: bash -c '[ -S /ipc/node.socket ]'
      interval: 3m
      retries: 60
  ogmios:
    image: cardanosolutions/ogmios:v5.5.6-mainnet
    restart: always
    environment:
      - NODE_CONFIG_PATH=/config/cardano-node/config.json
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=1337
      - NODE_SOCKET_PATH=/ipc/node.socket
      - LOG_LEVEL=Info
    command: [ "sh", "-xc", "ogmios --node-socket ${NODE_SOCKET_PATH} --host ${LISTEN_HOST} --port ${LISTEN_PORT} --log-level ${LOG_LEVEL} --node-config ${NODE_CONFIG_PATH}" ]
    volumes:
      - node-ipc:/ipc
    depends_on:
      cardano-node:
        condition: service_healthy
