version: '3.9'

volumes:
  node-ipc:

networks:
  default:
    name: liqwid-bots

services:
  watchtower:
    image: containrrr/watchtower
    command: --interval 3600 --label-enable --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  init-container:
    container_name: init
    build:
      dockerfile: init-container/Dockerfile
      context: .
    environment:
      - CARDANO_NODE_DATA_FOLDER=/data
    volumes:
      - ${CARDANO_NODE_DATA_FOLDER:-$PWD/cardano-node-data}:/data
    restart: no
  cardano-node:
    container_name: cardano-node
    image: inputoutput/cardano-node:8.1.1
    restart: always
    environment:
      - NETWORK=mainnet
    volumes:
      - ${CARDANO_NODE_DATA_FOLDER:-$PWD/cardano-node-data}:/data
      - node-ipc:/ipc
    depends_on:
      init-container:
        condition: service_completed_successfully
    healthcheck:
      test: bash -c '[ -S /ipc/node.socket ]'
      interval: 3m
      retries: 60
    logging:
      options:
        max-size: 10m
        max-file: "5"
  ogmios:
    container_name: ogmios
    image: cardanosolutions/ogmios:v5.5.6-mainnet
    restart: always
    command:
      - --node-config
      - /node-config/mainnet/config.json
      - --node-socket
      - /ipc/node.socket
      - --host
      - 0.0.0.0
      - --port
      - "1337"
      - --log-level
      - Info
    volumes:
      - ${PWD}/config:/node-config
      - node-ipc:/ipc
    depends_on:
      cardano-node:
        condition: service_healthy
    logging:
      options:
        max-size: 10m
        max-file: "5"
  kupo:
    container_name: kupo
    image: cardanosolutions/kupo:v2.4.1
    restart: always
    command:
      - --node-config
      - /node-config/mainnet/config.json
      - --node-socket
      - /ipc/node.socket
      - --host
      - 0.0.0.0
      - --port
      - "1442"
      - --in-memory
      - --prune-utxo
      - --since
      - 83735993.ddeb4bf0e1daf4b510afaf479a48ae23570c10cea5f373f4077e850c0e21495d
      - --match
      - '*/*'
      - --log-level
      - Info
    volumes:
      - ${PWD}/config:/node-config
      - node-ipc:/ipc
    depends_on:
      cardano-node:
        condition: service_healthy
    logging:
      options:
        max-size: 10m
        max-file: "5"
  ada-bot:
    container_name: ada-bot
    image: ghcr.io/liqwid-labs/liqwid-liquidation-bot:main
    labels:
      - com.centurylinklabs.watchtower.enable = true
    restart: always
    environment:
      - WALLET_MNEMONIC=${WALLET_MNEMONIC_ADA:-}
      - MARKET=Ada
      - HEARTBEAT_ADDR=127.0.0.1
      - HEARTBEAT_PORT=2002
      - VERBOSE=${VERBOSE:-false}
      - LOGGER=${LOGGER:-NoColourLogger}

      - OGMIOS_HOST=${OGMIOS_HOST:-ogmios}
      - OGMIOS_PORT=${OGMIOS_PORT:-1337}
      - OGMIOS_SECURE=${OGMIOS_SECURE:-false}
      - OGMIOS_PATH=${OGMIOS_PATH:-}

      - KUPO_HOST=${KUPO_HOST:-kupo}
      - KUPO_PORT=${KUPO_PORT:-1442}
      - KUPO_SECURE=${KUPO_SECURE:-false}
      - KUPO_PATH=${KUPO_PATH:-}

      - INTERVAL=${INTERVAL:-5}
      - BUFFER=${BUFFER:-20000000}
      - CHECK_PROFIT=${CHECK_PROFIT:-true}
      - PROFIT_AMOUNT=${PROFIT_AMOUNT:-5}
      - ENABLE_REDEEMS=${ENABLE_REDEEMS:-true}
      - LIQWID_CONFIG=liqwid-mainnet-config.json

    depends_on:
      kupo:
        condition: service_healthy
      ogmios:
        condition: service_healthy
    logging:
      options:
        max-size: 10m
        max-file: "5"
